[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[headers]
  "/*.css" = {cache-control = "public, max-age=31536000, immutable"}
  "/*.js" = {cache-control = "public, max-age=31536000, immutable"}